In [4]:
pip install mdtraj

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 2.2 MB 33.3 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for mdtraj: filename=mdtraj-1.9.9-cp38-cp38-linux_x86_64.whl size=7796150 sha256=1c0ebf3f3b82875540e6fcb7699411ea6f4876f1991ebe11ba0abfa80528031b
  Stored in directory: /home/ly2571/.cache/pip/wheels/95/29/b8/258d40960f6d13d8b23759a41bead59d0609f09afc32cab492
Successfully built mdtraj
You should consider upgrading via the '/share/apps/python/3.8.6/intel/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np

In [3]:
from __future__ import print_function
import matplotlib.pyplot as plt
import itertools
import mdtraj as md
import mdtraj.testing

In [7]:
t = md.load_pdb("Data/1UBQ_processed.pdb")
print(t)

<mdtraj.Trajectory with 1 frames, 1405 atoms, 134 residues, and unitcells>


In [8]:
hbonds = md.baker_hubbard(t, periodic=False)
print("the Number of Hydrogen Bounds is ",len(hbonds))
print(hbonds)

the Number of Hydrogen Bounds is  57
[[   0    3  285]
 [  36   37  254]
 [  55   56 1044]
 [  75   76  221]
 [  91   92 1077]
 [ 113  114  188]
 [ 146  147  119]
 [ 160  161  126]
 [ 203  204   90]
 [ 236  237   54]
 [ 270  271   18]
 [ 286  287  335]
 [ 326  327  300]
 [ 352  353  869]
 [ 371  372  838]
 [ 386  387  344]
 [ 386  387  351]
 [ 400  401  351]
 [ 416  417  370]
 [ 432  434  836]
 [ 438  439  385]
 [ 448  449  399]
 [ 464  466  269]
 [ 470  471  415]
 [ 489  490  437]
 [ 506  507  447]
 [ 518  519  469]
 [ 540  541  488]
 [ 555  556  505]
 [ 621  622  594]
 [ 638  639  608]
 [ 650  651  580]
 [ 650  652  437]
 [ 655  656 1129]
 [ 668  669  788]
 [ 698  699 1094]
 [ 717  718  775]
 [ 754  755  736]
 [ 793  794  697]
 [ 812  813  939]
 [ 846  847  826]
 [ 870  871  922]
 [ 884  885  337]
 [ 903  904  314]
 [ 914  915  876]
 [ 914  915  883]
 [ 926  927  902]
 [ 947  948  913]
 [ 961  962  902]
 [1019 1020   35]
 [1034 1035  996]
 [1059 1060   74]
 [1078 1079  716]
 [1095 10

In [9]:
label = lambda hbond : '%s -- %s' % (t.topology.atom(hbond[0]), t.topology.atom(hbond[2]))
Num_hbonds = 0

for hbond in hbonds:
    Num_hbonds += 1
    print(label(hbond))
print("the Number of Hydrogen Bounds is ",Num_hbonds)

MET1-N -- VAL17-O
ILE3-N -- LEU15-O
PHE4-N -- SER65-O
VAL5-N -- ILE13-O
LYS6-N -- LEU67-O
THR7-N -- LYS11-O
THR9-N -- THR7-OG1
GLY10-N -- THR7-O
ILE13-N -- VAL5-O
LEU15-N -- ILE3-O
VAL17-N -- MET1-O
GLU18-N -- ASP21-OD2
ASP21-N -- GLU18-O
ILE23-N -- ARG54-O
GLU24-N -- ASP52-O
ASN25-N -- THR22-OG1
ASN25-N -- THR22-O
VAL26-N -- THR22-O
LYS27-N -- ILE23-O
LYS27-NZ -- ASP52-OD2
ALA28-N -- GLU24-O
LYS29-N -- ASN25-O
LYS29-NZ -- GLU16-O
ILE30-N -- VAL26-O
GLN31-N -- LYS27-O
ASP32-N -- ALA28-O
LYS33-N -- LYS29-O
GLU34-N -- ILE30-O
GLY35-N -- GLN31-O
GLN40-N -- PRO37-O
GLN41-N -- PRO38-O
GLN41-NE2 -- ILE36-O
GLN41-NE2 -- LYS27-O
ARG42-N -- VAL70-O
ARG42-NE -- GLN49-NE2
ILE44-N -- HIS68-O
PHE45-N -- LYS48-O
LYS48-N -- PHE45-O
LEU50-N -- LEU43-O
GLU51-N -- TYR59-OH
ARG54-N -- GLU51-O
THR55-N -- ASP58-OD1
LEU56-N -- ASP21-O
SER57-N -- PRO19-O
ASP58-N -- THR55-OG1
ASP58-N -- THR55-O
TYR59-N -- LEU56-O
ASN60-N -- SER57-O
ILE61-N -- LEU56-O
GLU64-N -- GLN2-O
SER65-N -- GLN62-O
LEU67-N -- PHE4-O
HIS6

In [10]:
DSSP = mdtraj.compute_dssp(t, simplified=True)
DSSP

array([['C', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'C', 'C', 'C', 'E', 'E',
        'E', 'E', 'E', 'C', 'C', 'C', 'C', 'C', 'E', 'H', 'H', 'H', 'H',
        'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H',
        'H', 'E', 'E', 'E', 'E', 'E', 'C', 'C', 'E', 'E', 'C', 'C', 'C',
        'C', 'C', 'E', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C',
        'E', 'E', 'E', 'E', 'E', 'E', 'C', 'C', 'C', 'C', 'C', 'NA',
        'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA',
        'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA',
        'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA',
        'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA',
        'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA',
        'NA', 'NA']], dtype='<U2')

In [13]:
unique, counts = np.unique(DSSP, return_counts=True)
Statistics=dict(zip(unique, counts))
Statistics

{'C': 32, 'E': 26, 'H': 18, 'NA': 58}